 
INSERT INTO ACCOUNT (
	ACCOUNT_NUMBER, 
	BALANCE
	) VALUES
  (1, 100);
  
  
INSERT INTO ACCOUNT (
	ACCOUNT_NUMBER, 
	BALANCE
	) VALUES
  (2, 200);
  
INSERT INTO ACCOUNT (
	ACCOUNT_NUMBER, 
	BALANCE
	) VALUES
  (3, 300);

  
INSERT INTO TRANSACTION (
	TRANSACTION_ID, 
	SOURCE_ACCOUNT_NUMBER, 
	DESTINATION_ACCOUNT_NUMBER,
	AMOUNT) VALUES
  (4, 1, 2, 2);
  
INSERT INTO TRANSACTION (
	TRANSACTION_ID, 
	SOURCE_ACCOUNT_NUMBER, 
	DESTINATION_ACCOUNT_NUMBER,
	AMOUNT) VALUES
  (2, 2, 3, 34);
  
INSERT INTO TRANSACTION (
	TRANSACTION_ID, 
	SOURCE_ACCOUNT_NUMBER, 
	DESTINATION_ACCOUNT_NUMBER,
	AMOUNT) VALUES
  (3, 3, 1, 21);
  
CREATE SEQUENCE TRANSACTION_SEQUENCE
  MINVALUE 1
  MAXVALUE 1000000
  START WITH 5
  INCREMENT BY 1
  CACHE 100;  
  
COMMIT;