DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS TRANSACTION;


CREATE TABLE ACCOUNT (
  ACCOUNT_NUMBER INT AUTO_INCREMENT  PRIMARY KEY,
  BALANCE FLOAT
);

CREATE TABLE TRANSACTION (
  TRANSACTION_ID INT AUTO_INCREMENT  PRIMARY KEY,
  SOURCE_ACCOUNT_NUMBER INT,
  DESTINATION_ACCOUNT_NUMBER INT,
  AMOUNT FLOAT,
  FOREIGN KEY (SOURCE_ACCOUNT_NUMBER) REFERENCES ACCOUNT(ACCOUNT_NUMBER),
  FOREIGN KEY (DESTINATION_ACCOUNT_NUMBER) REFERENCES ACCOUNT(ACCOUNT_NUMBER)
);


COMMIT;